In [1]:
from sklearn import datasets, cross_validation, ensemble, metrics, neighbors
import numpy as np
import pylab as plt
%pylab inline

/home/artem/miniconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/home/artem/miniconda2/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


Populating the interactive namespace from numpy and matplotlib


/home/artem/miniconda2/lib/python2.7/site-packages/IPython/core/magics/pylab.py:161: UserWarning: pylab import has clobbered these variables: ['plt']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


In [2]:
digits = datasets.load_digits()
X = digits.data
y = digits.target

In [3]:
from sklearn import model_selection

In [3]:
a, b = np.arange(12).reshape((6, 2)), range(6)

In [4]:
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [10]:
b

[0, 1, 2, 3, 4, 5]

In [71]:
a_train, a_test, b_train, b_test = cross_validation.train_test_split(a, b, test_size=0.3, random_state=1)

In [72]:
a_train

array([[ 8,  9],
       [ 0,  1],
       [ 6,  7],
       [10, 11]])

In [73]:
a_test

array([[4, 5],
       [2, 3]])

In [37]:
X_train, X_test, y_train, y_test = cross_validation.train_test_split(X, y, test_size=0.25, random_state=0)

In [3]:
test_size = int(len(y) * 0.25)
X_train, X_test, y_train, y_test = (
  X[:-test_size], X[-test_size:],
  y[:-test_size], y[-test_size:])

In [ ]:
можно для каждого классифицируемого объекта составлять список пар 
(расстояние до точки из обучающей выборки, метка класса в этой точке), 
затем сортировать этот список 
(по умолчанию сортировка будет сначала по первому элементу пары, затем по второму), 
а затем брать первый элемент (с наименьшим расстоянием).

In [ ]:
0.00888888888889
0.02

In [4]:
KNN = neighbors.KNeighborsClassifier(n_neighbors = 1)
KNN.fit(X_train, y_train)
num1 = 1 - metrics.accuracy_score(y_test, KNN.predict(X_test))
print num1
# num1 = metrics.mean_absolute_error(y_test, KNN.predict(X_test))

0.0378619153675


In [5]:
X1 = KNN.predict(X_test)

In [6]:
num1 = 0
for i in xrange(len(y_test)):
    if (X1[i] != y_test[i]):
        num1 += 1
num1 /= float(len(y_test))
print num1

0.0378619153675


In [7]:
with open("1.txt", "w") as fout:
    fout.write(str(num1))
print num1

0.0378619153675


In [8]:
m = len(y_train)

In [9]:
def oneNN(x):
    pair = np.zeros((m, 2))
    for i in xrange(m):
        pair[i][0] = np.linalg.norm(x - X_train[i])
        pair[i][1] = y_train[i]
    pair = sorted(pair, key = lambda t: (t[0],t[1]))
    return pair[0][1]

In [10]:
oneNN(X_test[3])

4.0

In [11]:
y_test[3]

4

In [12]:
num1 = 0
for i in xrange(len(y_test)):
    if (oneNN(X_test[i]) != y_test[i]):
        num1 += 1
num1 /= float(len(y_test))
with open("1.txt", "w") as fout:
    fout.write(str(num1))
print num1

0.0378619153675


In [13]:
rf_classifier = ensemble.RandomForestClassifier(n_estimators = 1000)
rf_classifier.fit(X_train, y_train)
num2 = 1 - metrics.accuracy_score(y_test, rf_classifier.predict(X_test))
with open("2.txt", "w") as fout:
    fout.write(str(num2))
print num2

0.0645879732739


In [14]:
X2 = rf_classifier.predict(X_test)

In [15]:
num2 = 0
for i in xrange(len(y_test)):
    if (X2[i] != y_test[i]):
        num2 += 1
num2 /= float(len(y_test))
# num2 = (y_test, rf_classifier.predict(X_test))
with open("2.txt", "w") as fout:
    fout.write(str(num2))
print num2

0.0645879732739


In [48]:
num2 = 0.0
# with open("1.txt", "w") as fout:
#     fout.write(str(num2))
with open("2.txt", "w") as fout:
    fout.write("0.98")